apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: docker-flaskapp
  name: docker-flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-flaskapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-flaskapp
    spec:
      containers:
      - image: otoshev/docker-flaskapp:v1
        name: docker-flaskapp
        resources: {}
status: {}
