apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-26T19:16:11Z"
  labels:
    app: flask-app
  name: flask-app-nodeport
  namespace: o-toshev
  resourceVersion: "2727265"
  uid: 1b53fa61-0287-4c46-812c-39aec1e722a8
spec:
  clusterIP: 10.233.46.175
  clusterIPs:
  - 10.233.46.175
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30886
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
